struct graph *create_graph(struct graph *);
int insert_vertex(struct graph *,char);
struct vertex * find_vertex(struct graph *, char);
int insert_edge(struct graph *,char,char);
int edge_delete(struct graph *,char,char);
int vertex_delete(struct graph *,char);
int find_edge(struct graph *,char,char);
void show_edge(struct graph *);
void BFS(struct graph *,char,int);
void DFS_visit(struct graph *,char,int);
void DFS(struct graph *);
void option1(struct graph *,int);
void option2(struct graph *,int);
void directed(struct graph *,int);
void undirected(struct graph *,int);
void vertex_detail(struct graph *,char);
void print_path(struct graph *,char ,char );
int distance(struct graph *,char ,char );
void matrix_rep(struct graph *);
void free_graph(struct graph *);
